name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.x.x

    - name: Restore dependencies
      run: dotnet restore ./Mybarber-API/Mybarber

    - name: Build
      run: dotnet build --no-restore ./Mybarber-API/Mybarber

    - name: Test
      run: dotnet test --no-build --verbosity normal ./Mybarber-API/Mybarber

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: dantemds/mybarber
        tags: latest
        registry: docker.io
        dockerfile: ./Mybarber-API/Mybarber/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
