name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.x.x

    - name: Restore dependencies
      run: dotnet restore ./Mybarber-API/Mybarber

    - name: Build
      run: dotnet build --no-restore ./Mybarber-API/Mybarber

    - name: Test
      run: dotnet test --no-build --verbosity normal ./Mybarber-API/Mybarber

    - name: Login Docker
     uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dantemds/mybarber:latest
      
